version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      input_path: ${input_path}
      video_download: ${video_download}
      video_url: ${video_url}
      name_video_downloaded: ${name_video_downloaded}
      output_path: ${output_path}
      method_detection: ${method_detection}
      start_frame: ${start_frame}
      step_frame: ${step_frame}
      end_frame: ${end_frame}
      max_frame: ${max_frame}
      are_warped: ${are_warped}
      are_culled: ${are_culled}
      are_saved_landmarks: ${are_saved_landmarks}
      is_saved_rectangle: ${is_saved_rectangle}
  redis:
    image: "redis:alpine"